#!/bin/bash

export PATH=/usr/local/bin:$PATH

LINT=$(which swiftlint)

if [[ -e "${LINT}" ]]; then
	echo "SwiftLint Start..."
else
	echo "SwiftLint does not exist, download from https://github.com/realm/SwiftLint"
	exit 1
fi

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  swiftformat "${line}";
  git add "$line";
done