name: CI - Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Build iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app

      - name: Build iOS app
        run: exec ./.github/scripts/test_app.sh